# config

brand: @ntalbs
cover: http://37.media.tumblr.com/tumblr_m4dnbwaHm81rvf4w6o1_1280.jpg

# Content
excerpt_link: Read More

# Miscellaneous
rss:
google_analytics: UA-2098194-3

menu:
  Archives: /archives
  Tags: /tags
  About: /about
